const AvailableSpecsSeed = [
  { ar_spec_name: "التقنية", en_spec_name: "Technololgy" },
  { ar_spec_name: "نطاق الـ 2g", en_spec_name: "2g band" },
  { ar_spec_name: "نطاق الـ 3g", en_spec_name: "3g band" },
  { ar_spec_name: "نطاق الـ 4g", en_spec_name: "4g band" },
  { ar_spec_name: "نطاق الـ 5g", en_spec_name: "5g band" },
  { ar_spec_name: "السرعة", en_spec_name: "Speed" },
  { ar_spec_name: "تم الاعلان في", en_spec_name: "Announced" },
  { ar_spec_name: "الحالة", en_spec_name: "Status" },
  { ar_spec_name: "الأبعاد", en_spec_name: "Dimensions" },
  { ar_spec_name: "الوزن", en_spec_name: "Weight" },
  { ar_spec_name: "بنية الهاتف", en_spec_name: "Build" },
  { ar_spec_name: "شريحة الهاتف", en_spec_name: "SIM" },
  { ar_spec_name: "النوع", en_spec_name: "Type" },
  { ar_spec_name: "الحجم", en_spec_name: "Size" },
  { ar_spec_name: "الدقة", en_spec_name: "Resolution" },
  { ar_spec_name: "الحماية", en_spec_name: "Protection" },
  { ar_spec_name: "نظام التشغيل", en_spec_name: "Operating System" },
  { ar_spec_name: "نوع المعالج", en_spec_name: "Chipset" },
  { ar_spec_name: "وحدة المعالجة المركزية (CPU)", en_spec_name: "CPU" },
  { ar_spec_name: "معالج الرسوميات", en_spec_name: "GPU" },
  { ar_spec_name: "مدخل كارت ذاكرة", en_spec_name: "Card slot" },
  { ar_spec_name: "الداخلية", en_spec_name: "Internal" },
  { ar_spec_name: "نوع الكاميرا", en_spec_name: "Camera Type" },
  { ar_spec_name: "مميزات", en_spec_name: "Features" },
  { ar_spec_name: "الفيديو", en_spec_name: "Video" },
  {
    ar_spec_name: "الكاميرا الأمامية (السيلفي)",
    en_spec_name: "Selfie Camera Type",
  },
  {
    ar_spec_name: "مميزات الكاميرا الأمامية",
    en_spec_name: "Selfie Features",
  },
  { ar_spec_name: "الفيديو (سيلفي)", en_spec_name: "Selfie Video" },
  { ar_spec_name: "مكبر الصوت", en_spec_name: "Loudspeaker" },
  { ar_spec_name: "فتحة 3.5 مم", en_spec_name: "3.5mm jack" },
  { ar_spec_name: "الشبكات اللاسلكية (Wi-Fi)", en_spec_name: "WLAN" },
  { ar_spec_name: "بلوتوث", en_spec_name: "Bluetooth" },
  {
    ar_spec_name: "نظام تحديد المواقع (GPS)",
    en_spec_name: "Global Positioning System (GPS)",
  },
  {
    ar_spec_name: "الاتصال قريب المدى (NFC)",
    en_spec_name: "Near Field Communication (NFC)",
  },
  { ar_spec_name: "الراديو", en_spec_name: "Radio" },
  { ar_spec_name: "مدخل USB", en_spec_name: "USB" },
  { ar_spec_name: "المستشعرات", en_spec_name: "Sensors" },
  { ar_spec_name: "نوع البطارية", en_spec_name: "Battery Type" },
  { ar_spec_name: "الشحن", en_spec_name: "Charging" },
  { ar_spec_name: "وضع الإستعداد", en_spec_name: "Stand-by" },
  { ar_spec_name: "وضع تشغيل الموسيقى", en_spec_name: "Music play" },
  { ar_spec_name: "الألوان", en_spec_name: "Colors" },
  { ar_spec_name: "الإصدارات", en_spec_name: "Models" },
  {
    ar_spec_name: "معدل الامتصاص النوعي SAR",
    en_spec_name: "Specific absorption rate (SAR)",
  },
  { ar_spec_name: "السعر", en_spec_name: "Price" },
  { ar_spec_name: "الأداء", en_spec_name: "Performance" },
  { ar_spec_name: "الشاشة", en_spec_name: "Display" },
  { ar_spec_name: "الكاميرا", en_spec_name: "Camera" },
  {
    ar_spec_name: "اختبار مكبر الصوت",
    en_spec_name: "Loudspeaker Test",
  },
  { ar_spec_name: "عمر البطارية", en_spec_name: "Battery life" },
];
module.exports = AvailableSpecsSeed;
